### ISSUE TITLE
perf-dump link broken

### ISSUE THREAD

**Issue by aurotripathy** [tzislam/Dashing#1]
Hi, thanks for your repo and work.
The perf-dump link is broken.
Could you please state if its the same as `https://github.com/LLNL/perf-dump`

**Comment by tzislam** [comment]
Yes, the above link is correct -- however we extended the above perf-dump library to support multi-threaded data collection. That extension has not been pushed to the LLNL's repo yet. LLNL's version is sufficient to get you started with perfdump, and if you have an MPI application -- this is all you would need. Thank you for bringing the broken link to my attention. I will fix it.

**Comment by tzislam** [comment]
The perf-dump link has been fixed.
